deploy_script: >
  git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${OWNER}/${REPO}.git
  cd deploys
  ls -la

remove_script: 'echo remove'

production:
  url: 'http://test.com'

review:
  url: 'http://test.com'

staging:
  url: 'http://test.com'
