review:
  cluster: staging
  environment: pr{{ number }}
  transient_environment: true
  production_environment: false
  auto_merge: false
  payload: {}
production:
  # deploy_on: refs/heads/master
  cluster: production
  environment: production
  transient_environment: false
  production_environment: true
  auto_merge: false
  payload: {}
