review:
  cluster: staging
  environment: pr{{ number }}
  transient_environment: true
  production_environment: false
  auto_merge: false
  payload: {}
  required_contexts: []
staging:
  cluster: staging
  environment: staging
  transient_environment: true
  production_environment: false
  auto_merge: false
  payload: {}
  required_contexts: []
production:
  auto_deploy_on: refs/heads/master
  cluster: production
  environment: production
  transient_environment: false
  production_environment: true
  auto_merge: false
  payload: {}
